global SourceToDestNameMapping
SourceToDestNameMapping = {'gs_DER_battery_storage': ['ElectricDataset/Cobb_DER_battery_storage'],
                           'gs_row': ['LandDataset/RightOfWay'],
                           'gs_cadedge': ['LandDataset/Parcel_Lines'],
                           'st_misc_fields': ['WorkAndDesign/Cobb_WorkRequest'],
                           'gs_fiber_equipment': ['ElectricDataset/Cobb_FiberEquipment'],
                           'gs_njuns_ntg_pole_owner': ['Cobb_njuns_ntg_pole_owner'],
                           'gs_misc_text': ['ElectricDataset/MiscTextAnno'],
                           'gs_fiber_cable': ['ElectricDataset/CommunicationCable'],
                           'gs_misclab': ['ElectricDataset/MiscLabel'],
                           'gs_roads': ['LandDataset/StreetCenterline'],
                           'gs_lineman_service_area': ['ElectricDataset/LinemanServiceArea'],
                           'gs_taxdistrict': ['LandDataset/TaxDistrict'],
                           'gs_easement': ['LandDataset/Easement'],
                           'gs_elbow': ['ElectricDataset/Switch'],
                           'gs_hydrology_annotation': ['LandDataset/HydrologyLabel'],
                           'gs_surface_structure': ['ElectricDataset/SurfaceStructure', 'ElectricDataset/UndergroundStructure'],
                           'gs_span_guy': ['ElectricDataset/SpanGuy'],
                           'gs_county': ['LandDataset/County'],
                           'gs_overcurrent_device': ['ElectricDataset/Fuse', 'ElectricDataset/DynamicProtectiveDevice', 'FUSEUNIT', 'RECLOSERUNIT', 'SECTIONALIZERUNIT'],
                           'gs_span': ['ElectricDataset/PriOHElectricLineSegment', 'ElectricDataset/SecOHElectricLineSegment',
                                                          'ElectricDataset/PriUGElectricLineSegment', 'ElectricDataset/SecUGElectricLineSegment',
                                                          'ElectricDataset/BusBar', 'CONDUCTORINFO'],
                           'gs_abandoned_conduit': ['ElectricDataset/AbandonedConduitLine'],
                           'gs_miscbndy': ['LandDataset/MiscellaneousBoundaryArea'],
                           'gs_swgrbus': ['ElectricDataset/BusBar'],
                           'gs_plotbndy': ['LandDataset/PlotBoundary'],
                           'gs_faultind': ['ElectricDataset/MiscNetworkFeature'],
                           'gs_subnetwork_trunk': ['ElectricDataset/Cobb_SubnetworkTrunk'],
                           'gs_foreign_attachment': ['JOINTUSEATTACHMENT'],
                           'gs_board_district': ['LandDataset/BoardDistrict'],
                           'gs_voltage_regulator': ['ElectricDataset/VoltageRegulator', 'VOLTAGEREGULATORUNIT'],
                           'gs_DER_microturbine': ['ElectricDataset/Cobb_DER_microturbine'],
                           'gs_building': ['LandDataset/Building'],
                           'gs_abandoned_span': ['ElectricDataset/AbandonedElectricLineSegment', 'CONDUCTORINFO'],
                           'gs_electric_station': ['ElectricDataset/ElectricStation'],
                           'gs_transformer': ['ElectricDataset/Transformer', 'TRANSFORMERUNIT'],
                           'gs_conduit': ['ElectricDataset/ConduitLine'],
                           'gs_switch': ['ElectricDataset/Switch'],
                           'gs_substation_area': ['ElectricDataset/SubstationArea'],
                           'gs_intersections': ['LandDataset/StreetIntersection'],
                           'gs_subnetwork': ['ElectricDataset/Cobb_Subnetwork'],
                           'gs_right_of_way': ['LandDataset/RightOfWay'],
                           'gs_hydrology_line': ['LandDataset/HydrologyLine'],
                           'gs_municipal': ['LandDataset/Municipal'],
                           'gs_gps': ['LandDataset/GPSPoint'],
                           'open_points_PriOH': ['ElectricDataset/OpenPoint'],
                           'gs_easement_label': ['LandDataset/EasementLabel'],
                           'gs_hydrology_poly': ['LandDataset/HydrologyPoly'],
                           'gs_subdivision': ['LandDataset/Subdivision'],
                           'gs_suiteline': ['LandDataset/SuiteLine'],
                           'gs_swgrbus': ['ElectricDataset/BusBar'],
                           'st_workorder_ref': ['WorkAndDesign/Cobb_WorkRequest'],
                           'gs_service_point': ['ElectricDataset/ServicePoint', 'ElectricDataset/MeterPoint', 'ElectricDataset/PrimaryMeter'],
                           'gs_capacitor_bank': ['ElectricDataset/PFCorrectingEquipment', 'CAPACITORUNIT', 'CAPACITORCONTROL'],
                           'gs_street_light': ['ElectricDataset/Streetlight'],
                           'open_points_PriUG': ['ElectricDataset/OpenPoint'],
                           'gs_locationgrid': ['LandDataset/LocationGrid'],
                           'gs_landmark_label': ['LandDataset/LandmarkLabel'],
                           'gs_state': ['LandDataset/State'],
                           'gs_DER_PV_panel': ['ElectricDataset/Cobb_DER_PV_Panel'],
                           'gs_swgear': ['ElectricDataset/SwitchingFacility'],
                           'gs_attachment': ['JOINTUSERATTACHMENT'],
                           'gs_gndpoint': ['LandDataset/Cobb_GndPoint'],
                           'gs_building_label': ['LandDataset/BuildingLabel'],
                           'gs_tower': ['ElectricDataset/Tower'],
                           'gs_svcterr': ['LandDataset/ServiceTerritory'],
                           'gs_anchor_guy': ['ElectricDataset/AnchorGuy'],
                           'gs_landmark': ['LandDataset/Landmark'],
                           'gs_stub_pole': ['ElectricDataset/StubPole'],
                           'GS_ZIPCODE': ['LandDataset/ZipCode'],
                           'gs_railroad': ['LandDataset/Railroad'],
                           'gs_DER_SOFC': ['ElectricDataset/Cobb_DER_SOFC'],
                           'gs_transcond': ['ElectricDataset/TransmissionLine'],
                           'gs_support_structure': ['ElectricDataset/SupportStructure'],
                           'gs_roadedge': ['LandDataset/RoadEdge'],
                           'gs_address': ['LandDataset/Address']                           
                           }                        
